
--SUBQUERY
SET STATISTICS IO ON
SELECT U.NAMESURNAME,COUNT(B.ID) AS YAPILAN_ALISVERİS
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
GROUP BY U.NAMESURNAME

SET STATISTICS IO ON
SELECT U.ID, U.NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0



-- sub query ile müşteri bilgisi edinme

SELECT ID,NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS ITEMCOUNT_
FROM USER_ U
WHERE 
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0


SELECT U.ID,U.NAMESURNAME,
COUNT(B.ID) AS BASKETCOUNT,MIN(B.CREATEDDATE) AS FIRSTBASKETDATE,
MAX(B.CREATEDDATE) AS LASTBASKETDATE, SUM(BD.TOTAL) AS TOTAL, COUNT(BD.ID) AS ITEMCOUNT_
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.ID,U.NAMESURNAME


--Müşterinin sepetine eklediği son ürün
SELECT ID,NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS ITEMCOUNT_,
(
SELECT ITEMNAME FROM ITEM WHERE ID IN
 (
    SELECT TOP 1  ITEMID FROM BASKETDETAIL WHERE BASKETID IN
	(
	   SELECT ID FROM BASKET WHERE USERID=U.ID
	) ORDER BY DATE_ DESC
 )
) AS LASTITEMNAME
FROM USER_ U
WHERE 
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0


SELECT U.ID,U.NAMESURNAME,BD.DATE_,I.ITEMNAME
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ITEMID
WHERE U.ID=39
ORDER BY BD.DATE_


SELECT U.ID,U.NAMESURNAME,BD.DATE_,I.ITEMNAME
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ITEMID
WHERE U.ID=102
ORDER BY BD.DATE_


SELECT U.ID,U.NAMESURNAME,BD.DATE_,I.ITEMNAME
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ITEMID
WHERE U.ID=36
ORDER BY BD.DATE_
