SELECT * FROM USER_ WHERE ID=5474

SELECT * FROM BASKET
SELECT * FROM BASKETDETAIL
SELECT * FROM PAYMENT
SELECT * FROM ORDER_
SELECT * FROM ORDERDETAIL
SELECT * FROM INVOICE
SELECT * FROM INVOICEDETAIL



SELECT *
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID

SELECT U.NAMESURNAME,B.*
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID

SELECT U.NAMESURNAME,B.CREATEDDATE, BD.AMOUNT,BD.PRICE,BD.TOTAL,
I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
A.ADDRESSTEXT,C.CITY,T.TOWN,D.DISTRICT,
INV.INVOICENO, INV.CARGOFICHENO,INV.DATE_ AS SHIPDATE
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN  ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID

--bir kullanıcının yaptığı alışveriş sayısı,adedi,toplam tutarı
SELECT U.NAMESURNAME ADSOYAD,
COUNT(DISTINCT B.ID) ,
COUNT(BD.ID) ALDIGI_URUN_SAYISI,
SUM(BD.AMOUNT) ALDIGI_URUN_MIKTARI,
SUM(TOTAL)TOPLAM_ODENEN
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN  ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY U.NAMESURNAME



--hangi şehirde toplam ne kadar satılmış
SELECT C.CITY AS SEHIR ,
COUNT(DISTINCT B.ID) AS ALISVERISSAYISI ,
COUNT(BD.ID) ALDIGI_URUN_SAYISI,
SUM(BD.AMOUNT) ALDIGI_URUN_MIKTARI,
SUM(TOTAL)TOPLAM_ODENEN
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN  ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY C.CITY


--en çok satış yapılan müşteriler
SELECT U.USERNAME_,U.NAMESURNAME,
SUM(BD.TOTAL) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.USERNAME_,U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC

--en çok satış yapIlan 10 müşteri
--TOP 10
SELECT TOP 10  U.USERNAME_,U.NAMESURNAME,
SUM(BD.TOTAL) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.USERNAME_,U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC

--en çok satış yapılan ürün kategorileri
SELECT I.CATEGORY1, I.CATEGORY2, I.CATEGORY3, SUM(OD.TOTALPRICE) AS TOTAL
FROM ITEM I
INNER JOIN ORDERDETAIL OD ON OD.ITEMID=I.ID
INNER JOIN ORDER_ O ON O.ID=OD.ORDERID
WHERE I.CATEGORY1='elektronik-gida-disi'
AND I.CATEGORY2='beyaz-esya'
GROUP BY I.CATEGORY1,I.CATEGORY2,I.CATEGORY3
ORDER BY SUM(OD.TOTALPRICE) DESC


--Ocak 2021'de bizden alışveriş yapan kadın ve erkek müşteriler

SELECT U.GENDER,SUM(BD.TOTAL) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
WHERE B.CREATEDDATE BETWEEN '20210101' AND '20210131'
GROUP BY U.GENDER















