
SELECT * FROM USER_ WHERE ID=5474
SELECT * FROM ITEM WHERE ID=21563


SELECT * FROM BASKET
SELECT * FROM BASKETDETAIL
SELECT * FROM PAYMENT
SELECT * FROM ORDER_
SELECT * FROM ORDERDETAIL
SELECT * FROM INVOICE
SELECT * FROM INVOICEDETAIL