
SELECT * FROM USER_
WHERE USER_.ID=1

SELECT * FROM ADDRES
WHERE USERID=1

-- inner join
SELECT * FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=1

SELECT USER_.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=1

SELECT ADDRES.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=1

SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=1

SELECT * FROM ADDRES 
WHERE USERID=1

SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=2

SELECT USER_.NAMESURNAME FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=2

SELECT * FROM ADDRES 
WHERE USERID=2

DELETE FROM ADDRES 
WHERE USERID=2

SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=3

SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=4

DELETE FROM USER_ WHERE ID=4

SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
INNER JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=1