
--inner join
SELECT USER_.NAMESURNAME,ADDRES. * FROM USER_
INNER JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID IN(100,101,102)

SELECT * FROM USER_ WHERE ID=102

SELECT * FROM ADDRES WHERE USERID IN (100,101,102)

DELETE FROM ADDRES WHERE USERID=102


--left join
SELECT USER_.NAMESURNAME,ADDRES. * FROM USER_
LEFT JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID IN(100,101,102)

--right join
SELECT USER_.NAMESURNAME,ADDRES. * FROM USER_
RIGHT JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID IN(100,101,102)

--full join
SELECT USER_.NAMESURNAME,ADDRES. * FROM USER_
FULL JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID IN(100,101,102)

--left outer join left ile aynı
SELECT USER_.NAMESURNAME,ADDRES. * FROM USER_
LEFT OUTER JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID IN(100,101,102)

--right outer join right ile aynı
SELECT USER_.NAMESURNAME,ADDRES. * FROM USER_
RIGHT OUTER JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID IN(100,101,102)







