
SELECT * FROM SALES

SELECT *
FROM SALES
WHERE BRANCH ='Kocaeli Subesi'

SELECT SUM(LINENET)
FROM SALES
WHERE BRANCH ='Kocaeli Subesi'

SELECT SUM(LINENET)
FROM SALES

SELECT SUM(LINENET), COUNT(*)
FROM SALES
WHERE BRANCH ='Kocaeli Subesi'

SELECT *
FROM SALES
WHERE BRANCH ='Kocaeli Subesi'

SELECT SUM(LINENET), COUNT(*), MIN(LINENET),MAX(LINENET)
FROM SALES
WHERE BRANCH ='Kocaeli Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS ENDUSUKFIYAT,
MAX(LINENET) ASENYUKSEKFIYAT
FROM SALES
WHERE BRANCH ='İSTANBUL Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS ENDUSUKFIYAT,
MAX(LINENET) AS ENYUKSEKFIYAT,
AVG(LINENET) AS ORTALAMASATISFIYATI
FROM SALES
WHERE BRANCH ='İSTANBUL Subesi'


SELECT SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS ENDUSUKFIYAT,
MAX(LINENET) AS ENYUKSEKFIYAT,
AVG(LINENET) AS ORTALAMASATISFIYATI
FROM SALES
WHERE BRANCH ='Kocaeli Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS ENDUSUKFIYAT,
MAX(LINENET) AS ENYUKSEKFIYAT,
AVG(LINENET) AS ORTALAMASATISFIYATI
FROM SALES
WHERE BRANCH ='Ankara Subesi'


SELECT
BRANCH,
SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS ENDUSUKFIYAT,
MAX(LINENET) AS ENYUKSEKFIYAT,
AVG(LINENET) AS ORTALAMASATISFIYATI
FROM SALES
WHERE BRANCH ='Ankara Subesi'
GROUP BY BRANCH

SELECT
BRANCH,
SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS ENDUSUKFIYAT,
MAX(LINENET) AS ENYUKSEKFIYAT,
AVG(LINENET) AS ORTALAMASATISFIYATI
FROM SALES
--WHERE BRANCH ='Ankara Subesi'
GROUP BY BRANCH

SELECT COUNT(*) FROM SALES

--En çok satış yapan şubeler
SELECT BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH 
ORDER BY SUM(LINENET) DESC

SELECT TOP 10 BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH 
ORDER BY SUM(LINENET) DESC

SELECT TOP 10 BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH 
--ORDER BY SUM(LINENET) DESC

SELECT TOP 10 BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH 
ORDER BY 2 DESC --SATIŞ

SELECT BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH 
ORDER BY 2 DESC 

--Toplam satışı 50.000'den büyük olan mağazalar

SELECT BRANCH,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
HAVING SUM(LINENET)>50000

SELECT BRANCH,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
HAVING SUM(LINENET)>50000
ORDER BY 2 DESC

SELECT * FROM SALES WHERE BRANCH='Diyarbakır Subesi'

--Bir mağazanın gün bazlı satış rakamları

SELECT * FROM SALES
WHERE BRANCH='BURSA SUBESİ'
AND DATE_ = '2017-01-05'

SELECT BRANCH SUBE,
DATE_ TARİH,
SUM(LINENET) TOPLAMSATIS,
COUNT(*) AS SATIRSAYISI
FROM SALES
WHERE BRANCH='BURSA SUBESİ'
AND DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_

SELECT BRANCH SUBE,
DATE_ TARİH,
SUM(LINENET) TOPLAMSATIS,
COUNT(*) AS SATIRSAYISI
FROM SALES
WHERE BRANCH='BURSA SUBESİ'
--AND DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_

SELECT BRANCH SUBE,
DATE_ TARİH,
SUM(LINENET) TOPLAMSATIS,
COUNT(*) AS SATIRSAYISI
FROM SALES
WHERE BRANCH='BURSA SUBESİ'
--AND DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY DATE_

SELECT BRANCH SUBE,
DATE_ TARİH,
SUM(LINENET) TOPLAMSATIS,
COUNT(*) AS SATIRSAYISI
FROM SALES
WHERE BRANCH='ANKARA SUBESİ'
--AND DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY DATE_

SELECT * FROM SALES
WHERE BRANCH='ANKARA SUBESİ'
ORDER BY DATE_

--tüm mağazaların gün bazlı satış rakamları
SELECT BRANCH SUBE,
DATE_ TARİH,
SUM(LINENET) TOPLAMSATIS,
COUNT(*) AS SATIRSAYISI
FROM SALES
--WHERE BRANCH='ANKARA SUBESİ'
--AND DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY DATE_

SELECT BRANCH SUBE,
DATE_ TARİH,
SUM(LINENET) TOPLAMSATIS,
COUNT(*) AS SATIRSAYISI
FROM SALES
--WHERE BRANCH='ANKARA SUBESİ'
--AND DATE_ = '2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY BRANCH,DATE_

--bir günün mağaza bağlı satış rakamları
SELECT DATE_, BRANCH,SUM(LINENET)
FROM SALES
WHERE DATE_ ='20170105'
GROUP BY DATE_,BRANCH

SELECT DATE_, BRANCH,SUM(LINENET)
FROM SALES
WHERE DATE_ ='20170105'
GROUP BY DATE_,BRANCH
ORDER BY SUM(LINENET) DESC

SELECT DATE_, BRANCH,SUM(LINENET)
FROM SALES
--WHERE DATE_ ='20170105'
GROUP BY DATE_,BRANCH
ORDER BY DATE_, SUM(LINENET) DESC

--ürün kategorilerine göre satış rakamları

SELECT CATEGORY_NAME1,SUM(LINENET) 
FROM SALES
GROUP BY CATEGORY_NAME1


SELECT CATEGORY_NAME1,SUM(LINENET) 
FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL
GROUP BY CATEGORY_NAME1

SELECT CATEGORY_NAME1,BRAND,SUM(LINENET) 
FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL 
GROUP BY CATEGORY_NAME1,BRAND
ORDER BY SUM(LINENET) DESC

SELECT CATEGORY_NAME1,BRAND,SUM(LINENET) 
FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND CATEGORY_NAME1='GIDA'
GROUP BY CATEGORY_NAME1,BRAND
ORDER BY SUM(LINENET) DESC

--ürün markasına göre satışlar

SELECT BRAND,SUM(LINENET) 
FROM SALES
WHERE BRAND  IS NOT NULL
GROUP BY BRAND
ORDER BY SUM(LINENET) DESC

SELECT BRAND,CATEGORY_NAME1,SUM(LINENET) 
FROM SALES
WHERE BRAND  IS NOT NULL AND BRAND='ÜLKER'
GROUP BY BRAND,CATEGORY_NAME1
ORDER BY SUM(LINENET) DESC

SELECT BRAND,CATEGORY_NAME1,CATEGORY_NAME2,SUM(LINENET) 
FROM SALES
WHERE BRAND  IS NOT NULL AND BRAND='ÜLKER'
GROUP BY BRAND,CATEGORY_NAME1,CATEGORY_NAME2
ORDER BY SUM(LINENET) DESC

SELECT BRAND,CATEGORY_NAME1,CATEGORY_NAME2,SUM(LINENET) 
FROM SALES
WHERE BRAND  IS NOT NULL AND BRAND='ÜLKER'
GROUP BY BRAND,CATEGORY_NAME1,CATEGORY_NAME2
ORDER BY BRAND,CATEGORY_NAME1,CATEGORY_NAME2 DESC

--mağazaların müşteri sayısını hesaplama

SELECT BRANCH,COUNT(CLIENTNAME)
FROM SALES
GROUP BY BRANCH

SELECT BRANCH,COUNT(*)
FROM SALES
GROUP BY BRANCH

SELECT BRANCH,COUNT(ITEMCODE)
FROM SALES
GROUP BY BRANCH

SELECT BRANCH,COUNT(DATE_)
FROM SALES
GROUP BY BRANCH

SELECT * FROM SALES
WHERE BRANCH='ADANA SUBESİ'

SELECT DISTINCT CLIENTNAME 
FROM SALES
WHERE BRANCH='Amasya Subesi'

SELECT BRANCH,COUNT(DISTINCT CLIENTNAME)
FROM SALES
GROUP BY BRANCH

SELECT COUNT(DISTINCT CLIENTNAME)
FROM SALES

--bir müşterinin gittiği mağaza sayısı

SELECT CLIENTNAME,
COUNT(DISTINCT BRANCH)
FROM SALES
GROUP BY CLIENTNAME

SELECT * FROM SALES 
WHERE CLIENTNAME='Abdulkadir BİLCAN'

SELECT * FROM SALES 
WHERE CLIENTNAME='Kezban CİHANOGLU'

SELECT DISTINCT BRANCH FROM SALES
WHERE CLIENTNAME='Kezban CİHANOGLU'

--5'ten fazla mağazaya giden müşteriler
SELECT CLIENTNAME,COUNT(DISTINCT BRANCH)
FROM SALES
GROUP BY CLIENTNAME
HAVING COUNT(DISTINCT BRANCH)>5

--10'dan fazla mağazaya giden müşteriler
SELECT CLIENTNAME,COUNT(DISTINCT BRANCH)
FROM SALES
GROUP BY CLIENTNAME
HAVING COUNT(DISTINCT BRANCH)>10