/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [LOGICALREF]
      ,[ITEMCODE]
      ,[ITEMNAME]
      ,[FICHENO]
      ,[DATE_]
      ,[AMOUNT]
      ,[PRICE]
      ,[LINENETTOTAL]
      ,[LINENET]
      ,[BRANCHNR]
      ,[BRANCH]
      ,[SALESMAN]
      ,[CITY]
      ,[REGION]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[CLIENTCODE]
      ,[CLIENTNAME]
      ,[BRANDCODE]
      ,[BRAND]
      ,[CATEGORY_NAME1]
      ,[CATEGORY_NAME2]
      ,[CATEGORY_NAME3]
      ,[STARTDATE]
      ,[ENDDATE]
      ,[SPECODE]
      ,[CAPIBLOCK_CREADEDDATE]
  FROM [ETRADE].[dbo].[SALES]



  SELECT *
  FROM [ETRADE].[dbo].[SALES]

