
--WHERE Operatörü
SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME='Salih FAYDALI'

SELECT * FROM CUSTOMER
WHERE ID = 18

SELECT * FROM CUSTOMER
WHERE CITY='Rize'

SELECT * FROM CUSTOMER
WHERE CITY='İstanbul'

SELECT * FROM CUSTOMER
WHERE BIRTHDATE='1991-08-07'

SELECT * FROM CUSTOMER
WHERE BIRTHDATE='19971024'

SELECT * FROM CUSTOMER
WHERE CITY='Rize' AND DISTRICT='Pazar / Rize'

SELECT * FROM CUSTOMER
WHERE CITY='Rize' AND DISTRICT<>'Pazar / Rize'

SELECT * FROM CUSTOMER
WHERE AGE>52

SELECT * FROM CUSTOMER
WHERE AGE>81

SELECT * FROM CUSTOMER
WHERE AGE>80

SELECT * FROM CUSTOMER
WHERE AGE<23

SELECT * FROM CUSTOMER
WHERE AGE<22

SELECT * FROM CUSTOMER
WHERE AGE<=22

SELECT * FROM CUSTOMER
WHERE AGE<=23

SELECT * FROM CUSTOMER
WHERE BIRTHDATE>='19980101'

SELECT * FROM CUSTOMER
WHERE AGE BETWEEN 22 AND 23

SELECT * FROM CUSTOMER
WHERE AGE>=22 AND AGE<=23

SELECT * FROM CUSTOMER
WHERE BIRTHDATE BETWEEN '19980101' AND '19981231'


SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Rümeysa İNCEDAL'

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Rümeysa'

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Rümeysa%'

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%İNCE%' --içinde geçen

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%ÖRNEK' --ile biter

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'NAZLI%' --ile başlar

SELECT * FROM CUSTOMER
WHERE CITY = 'Isparta' 
AND DISTRICT IN ('ULUBORLU','YALVAÇ')

SELECT * FROM CUSTOMER
WHERE CITY = 'Isparta' 
AND DISTRICT NOT IN ('ULUBORLU','YALVAÇ')

SELECT * FROM CUSTOMER
WHERE CITY = 'Isparta' 
AND DISTRICT NOT IN ('ULUBORLU','YALVAÇ', 'Gelendost')

SELECT * FROM CUSTOMER
WHERE CITY = 'Isparta' 
AND DISTRICT NOT IN ('ULUBORLU','YALVAÇ', 'Gelendost')
AND GENDER = 'K'

SELECT * FROM CUSTOMER

DELETE FROM CUSTOMER WHERE ID=1

DELETE FROM CUSTOMER WHERE CUSTOMERNAME LIKE 'SERHAT%'

UPDATE CUSTOMER SET GENDER = 'ERKEK'
WHERE GENDER = 'E'

UPDATE CUSTOMER SET GENDER = 'KADIN'
WHERE GENDER = 'K'

SELECT * FROM CUSTOMER

--AND/OR Operatörü

SELECT * FROM CUSTOMER 
WHERE CITY='İSTANBUL'

SELECT * FROM CUSTOMER 
WHERE CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER 
WHERE CITY='İSTANBUL' 
AND CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER 
WHERE CITY='İSTANBUL' 
OR CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER 
WHERE CITY='İSTANBUL' 
AND 1<>1

SELECT * FROM CUSTOMER 
WHERE CITY='İSTANBUL' 
OR 1<>1

--Distinct

SELECT * FROM CUSTOMER
SELECT CITY FROM CUSTOMER
SELECT DISTINCT CITY FROM CUSTOMER

SELECT * 
FROM CUSTOMER 
WHERE CITY = 'İSTANBUL'

SELECT DISTINCT CITY, DISTRICT
FROM CUSTOMER WHERE CITY = 'İSTANBUL'

--ORDER BY

SELECT * FROM CUSTOMER
ORDER BY CUSTOMERNAME

SELECT * FROM CUSTOMER
ORDER BY CITY

SELECT * FROM CUSTOMER
ORDER BY CITY,CUSTOMERNAME

SELECT * FROM CUSTOMER
ORDER BY CITY, CUSTOMERNAME DESC

SELECT * FROM CUSTOMER
ORDER BY CITY ASC, CUSTOMERNAME DESC

SELECT * FROM CUSTOMER
ORDER BY CITY DESC, CUSTOMERNAME ASC

SELECT * FROM CUSTOMER
ORDER BY CITY DESC, BIRTHDATE

SELECT * FROM CUSTOMER
ORDER BY CITY 

SELECT * FROM CUSTOMER
ORDER BY 3 --şehire göre sırala

SELECT * FROM CUSTOMER
ORDER BY 2 --müşteri adına göre sırala

SELECT * FROM CUSTOMER
ORDER BY 1 --id'ye göre sırala

SELECT * FROM CUSTOMER
ORDER BY 6 --cinsiyete göre sırala

SELECT * FROM CUSTOMER
ORDER BY 6,3 --cinsiyet ve şehre göre sırala

--TOP Komutu
--MySqL'de LIMIT, Oracle'da ROWNUM komutu ile aynı

SELECT * FROM CUSTOMER

SELECT  TOP 5 * FROM CUSTOMER

SELECT  TOP 5 * FROM CUSTOMER
ORDER BY CUSTOMERNAME

SELECT  TOP 5 * FROM CUSTOMER
WHERE CITY='İSTANBUL'
ORDER BY CUSTOMERNAME

SELECT * FROM CUSTOMER
WHERE CITY='İSTANBUL'
ORDER BY CUSTOMERNAME

SELECT TOP 10 * FROM CUSTOMER
WHERE CITY='İSTANBUL'
ORDER BY CUSTOMERNAME


SELECT TOP 10 PERCENT * FROM CUSTOMER
WHERE CITY='İSTANBUL'
ORDER BY CUSTOMERNAME

SELECT TOP 50 PERCENT * FROM CUSTOMER
WHERE CITY='İSTANBUL'
ORDER BY CUSTOMERNAME

SELECT TOP 50 PERCENT * FROM CUSTOMER
ORDER BY CUSTOMERNAME











