
SELECT USER_.*,ADDRES.ADDRESSTEXT
FROM USER_
JOIN ADDRES ON USER_.ID=ADDRES.USERID
WHERE USER_.ID=1

SELECT U.*,A.ADDRESSTEXT
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
WHERE U.ID=1

-- birden fazla tablo ile join
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2
,C.CITY AS SEHIR,T.TOWN AS ILCE,
D.DISTRICT AS MAHALLE, 
A.ADDRESSTEXT AS ACIKADRES
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
WHERE U.ID=1

--her bir kullanıcının kaç tane adresi var onu listeleyelim
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2,
COUNT (A.ID) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
--WHERE U.ID=1
GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1, U.TELNR2

--en fazla adres sayısı
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2,
COUNT (A.ID) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
--WHERE U.ID=1
GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1, U.TELNR2
ORDER BY COUNT(A.ID) DESC

--adres sayısı bir tane olanlar
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2,
COUNT (A.ID) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
--WHERE U.ID=1
GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1, U.TELNR2
HAVING COUNT(A.ID)=1


--adres sayısı iki tane olanlar
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2,
COUNT (A.ID) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
--WHERE U.ID=1
GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1, U.TELNR2
HAVING COUNT(A.ID)=2


--adres sayısı üç tane olanlar
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2,
COUNT (A.ID) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
--WHERE U.ID=1
GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1, U.TELNR2
HAVING COUNT(A.ID)=3

--hangi şehirde kaç kullanıcımız var
SELECT 
C.CITY,COUNT(U.ID) AS KULLANICISAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY C.CITY ORDER BY 2 DESC


SELECT U.ID,U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,U.TELNR2 AS TELEFON2,
COUNT (A.ID) AS ADRESSAYISI,
COUNT (DISTINCT C.CITY) AS SEHIRSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY U.ID,U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1, U.TELNR2
HAVING COUNT (A.ID)<>COUNT(DISTINCT C.CITY)


SELECT * FROM ADDRES WHERE USERID=109