CREATE TABLE COUNTRY(
ID INT IDENTITY(1,1),
COUNTRY VARCHAR(100),
CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE TOWN(
ID INT IDENTITY(1,1),
TOWN VARCHAR(100),
CONSTRAINT [PK_TOWN] PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE DISTRICT(
ID INT IDENTITY(1,1),
DISTRICT VARCHAR(100),
CONSTRAINT [PK_DISTRICT] PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE CITY(
ID INT IDENTITY(1,1),
CITY VARCHAR(100),
CONSTRAINT [PK_CITY] PRIMARY KEY CLUSTERED (ID ASC))
