CREATE TABLE PAYMENT(
ID INT IDENTITY(1,1),
BASKETID INT,
TOTALPRICE FLOAT,
PAYMENTTYPE INT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(20),
ERROR_ VARCHAR(1000),
CONSTRAINT [PK_PAYMENT] PRIMARY KEY CLUSTERED (ID ASC))
